classDiagram
  class OptimizationMixin {
    optimizations : set
    apply_optimizations(sensor: rs_sensor)
    optimize_low_stereo_temperature(sensor: rs_sensor)
  }
  class Pipeline {
    opts
    resolver : SPResolver
    add_config(profiles: set[StreamProfile], pvid_device: PVID | None) None
    alive(stream_profile: StreamProfile | None)
    remove_config(profile: StreamProfile) None
    sensor(stream_profile: StreamProfile | None) Sensor
    start(stream_profile: StreamProfile | None) None
    stop(stream_profile: StreamProfile | None) None
    stream(stream_profile: StreamProfile) Stream
  }
  class PipelineOptions {
  }
  class RSSensor {
    close()
    is_healthy()
    open()
    start()
    stop()
  }
  class RSSensorOptions {
    max_asic_temperature : float
    max_projector_temperature : float
  }
  class Sensor {
    config
    opts
    state
    close()
    configure(config: SensorConfig)
    is_healthy()*
    open()
    start()
    stop()
  }
  class SensorCloseError {
  }
  class SensorConfig {
    stream : Stream | None
    stream_profiles : frozenset[StreamProfile]
  }
  class SensorError {
  }
  class SensorInfoError {
  }
  class SensorOpenError {
  }
  class SensorOptions {
  }
  class SensorStartError {
  }
  class SensorState {
    name
  }
  class SensorStopError {
  }
  class Stream {
    get() NDArray | None
    get_oldest() NDArray | None
    put(data: NDArray)
    wait(timeout_ms: int) NDArray
    wait_oldest(timeout_ms: int) NDArray | None
  }
  class StreamFormat {
    name
  }
  class StreamProfile {
    format
  }
  class VideoStreamProfile {
    fps : int
    height : int
    width : int
  }
  SensorCloseError --|> SensorError
  SensorInfoError --|> SensorError
  SensorOpenError --|> SensorError
  SensorStartError --|> SensorError
  SensorStopError --|> SensorError
  VideoStreamProfile --|> StreamProfile
  StreamProfile --> StreamFormat : format
  SensorOptions --o Sensor : opts
  PipelineOptions --o Pipeline : opts
